### ISSUE TITLE
Implementar el mapa

### ISSUE THREAD

**Issue by demency** [Alimentalos/Application#16]
Se debe implementar un mapa en la aplicación, luego se definirán sus características.

**Comment by edidk7** [comment]
Que mapa me recomiendas utilizar ?

**Comment by demency** [comment]
Cualquiera excepto Google Maps, idealmente open source y que no tenga costo la implementación, ya que puede contar con un tier gratuito para aplicaciones libres.

**Comment by edidk7** [comment]
Utilizare leaflet
