### ISSUE TITLE
Create wireframes module users

### ISSUE THREAD

**Issue by edidk7** [Alimentalos/Application#39]
Module users views of the mobile application.

**Comment by edidk7** [comment]
Wireframes designed.

![1](https://user-images.githubusercontent.com/16347165/84083953-90638180-a9b0-11ea-8d34-a7509977f769.png)

**Comment by edidk7** [comment]
@demency the invitation is only for users or also groups?

**Comment by edidk7** [comment]
@demency I wait your answer.

**Comment by demency** [comment]
Groups too, but not in the Users module. I think the Groups module.
