### ISSUE TITLE
Create wireframes module locations

### ISSUE THREAD

**Issue by edidk7** [Alimentalos/Application#41]
module to get the locations of the animals.

**Comment by edidk7** [comment]
Wireframes designed.

Animal selection flow:

1. Home start app
2. Selected animal
3. Get to route location  

![Web 1920 – 7](https://user-images.githubusercontent.com/16347165/84394352-d1cf7900-abca-11ea-931b-47a037c642ad.png)

I leave attached the XD file with its corresponding wireframes.
[alimentalos.zip](https://github.com/Alimentalos/Application/files/4765239/alimentalos.zip)

**Comment by edidk7** [comment]
process flow improvements in the process flow in feeding animals with photo post:

1. Home start app
2. Selected animal
3. Get to route location
4. Animals fed action button
5. Upload post with photo
6. Tag in groups

![Web 1920 – 8](https://user-images.githubusercontent.com/16347165/84448641-39acb080-ac19-11ea-9673-7035193ab7f6.png)


![Web 1920 – 9](https://user-images.githubusercontent.com/16347165/84448646-3d403780-ac19-11ea-9d3a-74cd59ecf873.png)

I leave attached the XD file with its corresponding wireframes.

[alimentalos.zip](https://github.com/Alimentalos/Application/files/4767768/alimentalos.zip)

**Comment by edidk7** [comment]
the flow is correct @demency ?

**Comment by demency** [comment]
@edidk7 Yeah sure.
